
default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sample
  pool: 5
  username: root
  password:
  host: localhost

test:
  <<: *default
  database: sample

production:
  <<: *default
  database: sample
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
